services:
  dev:
    build: ./docker
    ports:
      - "3030:3030"
    volumes:
      - ./presentation:/working-dir/presentation
      - ./dist:/working-dir/dist
    command: slidev /working-dir/presentation/slides.md --port 3030 --remote

  export:
    build: ./docker
    volumes:
      - ./presentation:/working-dir/presentation
      - ./dist:/working-dir/dist
    command: slidev export /working-dir/presentation/slides.md --output /working-dir/dist/slides.pdf
    profiles:
      - export
